# -*- coding: utf-8 -*-
import sys
import django

import re
import string
import os
import shutil
import threading
import json
import random
import Queue
import traceback

#语言
language_list = {
    u'英文':['ENABLE_ENGLISH','LANGUAGE_ENGLISH'],
    u'中文简体':['ENABLE_CHINESE','LANGUAGE_CHINESE'],
    u'俄语':['ENABLE_RSSIAN','LANGUAGE_RUSSIAN'],
    u'法语':['ENABLE_FRENCH','LANGUAGE_FRENCH'],
    u'德语':['ENABLE_GERMAN','LANGUAGE_GERMAN'],
    u'葡萄牙语':['ENABLE_PORTGESE','LANGUAGE_PORTGESE'],
    u'阿拉伯语':['ENABLE_ARABIC','LANGUAGE_ARABIC'],
    u'波斯语':['ENABLE_FARSI','LANGUAGE_FARSI'],
    u'蒙古语':['ENABLE_MONGOLIA','LANGUAGE_MONGOLIA'],
    u'泰语':['ENABLE_THAI','LANGUAGE_THAI'],
    u'西班牙语':['ENABLE_SPANISH','LANGUAGE_SPANISH'],
    u'罗马利亚语':['ENABLE_ROMANIAN','LANGUAGE_ROMANIAN'],
    u'意大利语':['ENABLE_ITALIA','LANGUAGE_ITALIA'],
    u'朝鲜语':['ENABLE_POLISH','LANGUAGE_POLISH'],
}

language = {
    u'英文':'ENG',
    u'中文简体':'CHI',
    u'俄语':'RSS',
    u'法语':'FRE',
    u'德语':'GER',
    u'葡萄牙语':'POR',
    u'阿拉伯语':'ARA',
    u'波斯语':'FAR',
    u'蒙古语':'MON',
    u'泰语':'THA',
    u'西班牙语':'SPA',
    u'罗马利亚语':'ROM',
    u'意大利语':'ITA',
    u'朝鲜语':'POL',
}
# 遥控
def IRlist():
    i = 0
    temp_keylist = []
    while i < 255:
        temp_key = str(hex(i))
        if i < 16:
            temp_key = temp_key.replace('0x','0x0')
        temp_keylist.append(temp_key)
        i = i+1;
        pass
    return temp_keylist

#按键
keypad = {
    'CH+':'UP',
    'CH-':'DOWN',
    'VOL+':'RIGHT',
    'VOL-':'LEFT',
    'POWER':'POWER',
    'SOURCE':'INPUT_SOURCE',
    'MENU':'MENU',
    'RIGHT':'RIGHT',
    'LEFT':'LEFT',
}

#屏参
panel_on_list = [
    'PANEL_DUAL_PORT',
    'PANEL_DOUBLE_CLOCK',
    'PANEL_SWAP_PORT',
    'PANEL_SWAP_ODD_ML',
    'PANEL_SWAP_EVEN_ML',
    'PANEL_SWAP_ODD_RB',
    'PANEL_SWAP_EVEN_RB',
    'PANEL_SWAP_ODD_RG',
    'PANEL_SWAP_EVEN_RG',
    'PANEL_SWAP_ODD_GB',
    'PANEL_SWAP_EVEN_GB',
    'ENABLE_BLACK_WHITE_CHANGE'
]

#PQ
C_PQ = {
    'ihc_r':'BK1C_4B',
    'ihc_g':'BK1C_4C',
    'ihc_b':'BK1C_4D',
    'ihc_c':'BK1C_4E',
    'ihc_m':'BK1C_4F',
    'ihc_y':'BK1C_50',
    'ihc_f':'BK1C_51',

    'ibc_r':'BK1C_23',
    'ibc_g':'BK1C_24',
    'ibc_b':'BK1C_25',
    'ibc_c':'BK1C_26',
    'ibc_m':'BK1C_27',
    'ibc_y':'BK1C_28',
    'ibc_f':'BK1C_29',

    'icc_r':'BK2B_C3',
    'icc_g':'BK2B_C4',
    'icc_b':'BK2B_C5',
    'icc_c':'BK2B_C6',
    'icc_m':'BK2B_C7',
    'icc_y':'BK2B_C8',
    'icc_f':'BK2B_C9',
}

#板型名称
boardList = [
    'BD_ZVT_MV56RUU_G',
    'BD_ZVT_MV56RUU_H',
    'BD_ZVT_MV56RUU_J',
    'BD_ZVT_MV56RJU_F',
    'BD_ZVT_MV56RJU_G',
    'BD_ZVT_MV56RJU_H'
]
def select_board(Boardname):
    if 'P813' in Boardname:
        str = 'BD_ZVT_MV56RUU_P813'
    elif 'PB813' in Boardname:
        str = 'BD_ZVT_MV56RUU_PB813'
    elif 'P671' in Boardname:
        str = 'BD_ZVT_MV56RUU_P671'
    elif 'P815' in Boardname:
        str = 'BD_ZVT_MV56RUU_P815'
    else :
        str = Boardname
    return str

border_80PIN_model = {
    'BD_ZVT_MV56RJU_B':'PROJ ?= R2_MELODY_ATV_MM_32MB_B_BLOADER',
    'BD_ZVT_MV56RJU_C':'PROJ ?= R2_MELODY_ATV_MM_32MB_C_BLOADER',
    'BD_ZVT_MV56RJU_CK':'PROJ ?= R2_MELODY_ATV_MM_32MB_CK_BLOADER',
    'BD_ZVT_MV56RJU_BK':'PROJ ?= R2_MELODY_ATV_MM_32MB_BK_BLOADER',
    'BD_ZVT_MV56RJU_D':'PROJ ?= R2_MELODY_ATV_MM_32MB_D_BLOADER',
    'BD_ZVT_MV56RJU_DK':'PROJ ?= R2_MELODY_ATV_MM_32MB_DK_BLOADER',
    'BD_ZVT_MV56RJU_F':'PROJ ?= R2_MELODY_ATV_MM_32MB_F_BLOADER',
    'BD_ZVT_MV56RJU_A8':'PROJ ?= R2_MELODY_ATV_MM_32MB_A8_BLOADER',
    'BD_ZVT_MV56RJU_P671':'PROJ ?= R2_MELODY_ATV_MM_32MB_P671_BLOADER',
    'BD_ZVT_MV56RJU_P671B':'PROJ ?= R2_MELODY_ATV_MM_32MB_P671B_BLOADER',
    'BD_ZVT_MV56RJU_P671C':'PROJ ?= R2_MELODY_ATV_MM_32MB_P671C_BLOADER',
    'BD_ZVT_MV56RJU_P672':'PROJ ?= R2_MELODY_ATV_MM_32MB_P672_BLOADER',
    'BD_ZVT_MV56RJU_P819':'PROJ ?= R2_MELODY_ATV_MM_32MB_P819_BLOADER',
    'BD_ZVT_MV56RJU_P819B':'PROJ ?= R2_MELODY_ATV_MM_32MB_P819B_BLOADER',
    'BD_ZVT_MV56RJU_P818':'PROJ ?= R2_MELODY_ATV_MM_32MB_P818_BLOADER',
    'BD_ZVT_MV56RJU_G':'PROJ ?= R2_MELODY_ATV_MM_32MB_G_BLOADER',
    'BD_ZVT_MV56RJU_H':'PROJ ?= R2_MELODY_ATV_MM_32MB_H_BLOADER',
    'BD_ZVT_MV56RJU_I':'PROJ ?= R2_MELODY_ATV_MM_32MB_I_BLOADER',
    'BD_ZVT_MV56RJU_P813':'PROJ ?= R2_MELODY_ATV_MM_32MB_P813_BLOADER',
    'BD_ZVT_MV56RJU_A81':'PROJ ?= R2_DS_V56RL_A81_BLOADER',
    'BD_ZVT_MV56RJU_BK1':'PROJ ?= R2_DS_V56RL_BK1_BLOADER',
    'BD_ZVT_MV56RJU_671A1':'PROJ ?= R2_DP_V56RL_671A1_BLOADER',


    'BD_ZVT_MV56RL_A8':'PROJ ?= R2_DS_V56RL_A81_BLOADER',
    'BD_ZVT_MV56RL_BK':'PROJ ?= R2_DS_V56RL_BK1_BLOADER',
    'BD_ZVT_MV56RL_671A':'PROJ ?= R2_DP_V56RL_671A1_BLOADER',
    'BD_ZVT_MV56RL_PA':'PROJ ?= R2_DS_V56RL_PA_BLOADER',
    'BD_ZVT_MV56RL_813E':'PROJ ?= R2_DP_V56RL_813E1_BLOADER',
    'BD_ZVT_MV56RL_813F':'PROJ ?= R2_DP_V56RL_813F1_BLOADER',
    'BD_ZVT_MV56RL_819A':'PROJ ?= R2_DP_V56RL_819A1_BLOADER',
    'BD_ZVT_MV56RL_H':'PROJ ?= R2_DS_V56RL_H_BLOADER',
    'BD_ZVT_MV56RL_816A':'PROJ ?= R2_DP_V56RL_816A1_BLOADER',
    'BD_ZVT_MV56RL_816B':'PROJ ?= R2_DP_V56RL_816B1_BLOADER',
    'BD_ZVT_MV56RL_813C':'PROJ ?= R2_DP_V56RL_813C1_BLOADER',
    'BD_ZVT_MV56RL_813D':'PROJ ?= R2_DP_V56RL_813D1_BLOADER',
    # 'BD_ZVT_MV56':'PROJ ?= R2_DS_V56RL_A81_BLOADER_ONLY',
    # 'BD_ZVT_MV56':'PROJ ?= R2_DS_V56RL_BK1_BLOADER_ONLY',
    # 'BD_ZVT_MV56':'PROJ ?= R2_DP_V56RL_671A1_BLOADER_ONLY',
    # 'BD_ZVT_MV56':'PROJ ?= R2_DS_V56RL_PA_BLOADER_ONLY',
    # 'BD_ZVT_MV56':'PROJ ?= R2_DP_V56RL_813E1_BLOADER_ONLY',
    # 'BD_ZVT_MV56':'PROJ ?= R2_DP_V56RL_813F1_BLOADER_ONLY',
    # 'BD_ZVT_MV56':'PROJ ?= R2_DP_V56RL_819A1_BLOADER_ONLY',
    # 'BD_ZVT_MV56':'PROJ ?= R2_DS_V56RL_H_BLOADER_ONLY',
    # 'BD_ZVT_MV56':'PROJ ?= R2_DP_V56RL_816A1_BLOADER_ONLY',
    # 'BD_ZVT_MV56':'PROJ ?= R2_DP_V56RL_816B1_BLOADER_ONLY',
    # 'BD_ZVT_MV56':'PROJ ?= R2_DP_V56RL_813C1_BLOADER_ONLY',
    # 'BD_ZVT_MV56':'PROJ ?= R2_DP_V56RL_813D1_BLOADER_ONLY',

}
border_128PIN_model = {
    'BD_ZVT_MV56RUU_P819':'PROJ ?= R2_MELODY_ATV_MM_64MB_P819_BLOADER',
    'BD_ZVT_MV56RUU_P816':'PROJ ?= R2_MELODY_ATV_MM_64MB_P816_BLOADER',
    'BD_ZVT_MV56RUU_A8':'PROJ ?= R2_MELODY_ATV_MM_64MB_A8_BLOADER',
    'BD_ZVT_MV56RUU_G':'PROJ ?= R2_MELODY_ATV_MM_64MB_G_BLOADER',
    'BD_ZVT_MV56RUU_E':'PROJ ?= R2_MELODY_ATV_MM_64MB_E_BLOADER',
    'BD_ZVT_MV56RUU_B':'PROJ ?= R2_MELODY_ATV_MM_64MB_B_BLOADER',
    'BD_ZVT_MV56RUU_PC':'PROJ ?= R2_MELODY_ATV_MM_64MB_PC_BLOADER',
    'BD_ZVT_MV56RUU_P813A':'PROJ ?= R2_MELODY_ATV_MM_64MB_P813A_BLOADER',
    'BD_ZVT_MV56RUU_P813B':'PROJ ?= R2_MELODY_ATV_MM_64MB_P813B_BLOADER',
    'BD_ZVT_MV56RUU_P813C':'PROJ ?= R2_MELODY_ATV_MM_64MB_P813C_BLOADER',
    'BD_ZVT_MV56RUU_P813D':'PROJ ?= R2_MELODY_ATV_MM_64MB_P813D_BLOADER',
    'BD_ZVT_MV56RUU_P813E':'PROJ ?= R2_MELODY_ATV_MM_64MB_P813E_BLOADER',
    'BD_ZVT_MV56RUU_P813F':'PROJ ?= R2_MELODY_ATV_MM_64MB_P813F_BLOADER',
    'BD_ZVT_MV56RUU_P671A':'PROJ ?= R2_MELODY_ATV_MM_64MB_P671A_BLOADER',
    'BD_ZVT_MV56RUU_P671B':'PROJ ?= R2_MELODY_ATV_MM_64MB_P671B_BLOADER',
    'BD_ZVT_MV56RUU_P671C':'PROJ ?= R2_MELODY_ATV_MM_64MB_P671C_BLOADER',
    'BD_ZVT_MV56RUU_P671D':'PROJ ?= R2_MELODY_ATV_MM_64MB_P671D_BLOADER',
    'BD_HL_V56G_DU':'PROJ ?= R2_MELODY_ATV_MM_64MB_GDU_BLOADER',
    'BD_ZVT_MV56RUU_H':'PROJ ?= R2_MELODY_ATV_MM_64MB_H_BLOADER',
    'BD_ZVT_MV56RUU_A':'PROJ ?= R2_MELODY_ATV_MM_64MB_A_BLOADER',
    'BD_ZVT_MV56RUU_J':'PROJ ?= R2_MELODY_ATV_MM_64MB_J_BLOADER',
    'BD_ZVT_MV56RUU_PB813A':'PROJ ?= R2_MELODY_ATV_MM_64MB_PB813A_BLOADER',
    'BD_ZVT_MV56RUU_PB813B':'PROJ ?= R2_MELODY_ATV_MM_64MB_PB813B_BLOADER',
    'BD_ZVT_MV56RUU_PB813C':'PROJ ?= R2_MELODY_ATV_MM_64MB_PB813C_BLOADER',
    'BD_ZVT_MV56RUU_PB813D':'PROJ ?= R2_MELODY_ATV_MM_64MB_PB813D_BLOADER',
    'BD_ZVT_MV56RUU_PB813E':'PROJ ?= R2_MELODY_ATV_MM_64MB_PB813E_BLOADER',
    'BD_ZVT_MV56RUU_PB813F':'PROJ ?= R2_MELODY_ATV_MM_64MB_PB813F_BLOADER',
    'BD_ZVT_MV56RUU_PB':'PROJ ?= R2_MELODY_ATV_MM_64MB_PB_BLOADER',
    'BD_ZVT_MV56RUU_P813PC':'PROJ ?= R2_MELODY_ATV_MM_64MB_P813PC_BLOADER',
    'BD_ZVT_MV56RUU_P815A':'PROJ ?= R2_MELODY_ATV_MM_64MB_P815A_BLOADER',
    'BD_ZVT_MV56RUU_P815B':'PROJ ?= R2_MELODY_ATV_MM_64MB_P815B_BLOADER',

    #PROJ ?= R2_MELODY_ATV_MM_64MB_BLOADER_ONLY
    #PROJ ?= R2_MELODY_ATV_MM_64MB_P819_BLOADER_ONLY
    #PROJ ?= R2_MELODY_ATV_MM_64MB_P816_BLOADER_ONLY
    #PROJ ?= R2_MELODY_ATV_MM_64MB_A8_BLOADER_ONLY
    #PROJ ?= R2_MELODY_ATV_MM_64MB_G_BLOADER_ONLY
    #PROJ ?= R2_MELODY_ATV_MM_64MB_E_BLOADER_ONLY
    #PROJ ?= R2_MELODY_ATV_MM_64MB_B_BLOADER_ONLY
    #PROJ ?= R2_MELODY_ATV_MM_64MB_PC_BLOADER_ONLY
    #PROJ ?= R2_MELODY_ATV_MM_64MB_P813A_BLOADER_ONLY
    #PROJ ?= R2_MELODY_ATV_MM_64MB_P813B_BLOADER_ONLY
    #PROJ ?= R2_MELODY_ATV_MM_64MB_P813C_BLOADER_ONLY
    #PROJ ?= R2_MELODY_ATV_MM_64MB_P813D_BLOADER_ONLY
    #PROJ ?= R2_MELODY_ATV_MM_64MB_P813E_BLOADER_ONLY
    #PROJ ?= R2_MELODY_ATV_MM_64MB_P813F_BLOADER_ONLY
    #PROJ ?= R2_MELODY_ATV_MM_64MB_P671A_BLOADER_ONLY
    #PROJ ?= R2_MELODY_ATV_MM_64MB_P671B_BLOADER_ONLY
    #PROJ ?= R2_MELODY_ATV_MM_64MB_P671C_BLOADER_ONLY
    #PROJ ?= R2_MELODY_ATV_MM_64MB_P671D_BLOADER_ONLY
    #PROJ ?= R2_MELODY_ATV_MM_64MB_GDU_BLOADER_ONLY
    #PROJ ?= R2_MELODY_ATV_MM_64MB_H_BLOADER_ONLY
    #PROJ ?= R2_MELODY_ATV_MM_64MB_A_BLOADER_ONLY
    #PROJ ?= R2_MELODY_ATV_MM_64MB_J_BLOADER_ONLY
    #PROJ ?= R2_MELODY_ATV_MM_64MB_PB813A_BLOADER_ONLY
    #PROJ ?= R2_MELODY_ATV_MM_64MB_PB813B_BLOADER_ONLY
    #PROJ ?= R2_MELODY_ATV_MM_64MB_PB813C_BLOADER_ONLY
    #PROJ ?= R2_MELODY_ATV_MM_64MB_PB813D_BLOADER_ONLY
    #PROJ ?= R2_MELODY_ATV_MM_64MB_PB813E_BLOADER_ONLY
    #PROJ ?= R2_MELODY_ATV_MM_64MB_PB813F_BLOADER_ONLY
    #PROJ ?= R2_MELODY_ATV_MM_64MB_PB_BLOADER_ONLY
    #PROJ ?= R2_MELODY_ATV_MM_64MB_P813PC_BLOADER_ONLY
    #PROJ ?= R2_MELODY_ATV_MM_64MB_P815A_BLOADER_ONLY
    #PROJ ?= R2_MELODY_ATV_MM_64MB_P815B_BLOADER_ONLY
}
#文件位置
def filepath(project_sys):
    py_replace_dat_dic = {
        u'count':4,
        u'mkfile':"/home/meng/%s"%(project_sys),
        u'chgfile':"/home/meng/%s/sftp.list"%(project_sys),
        u'dstfile':"/home/meng/%s/project/boarddef/include/CustomerConfig_AOTO.h"%(project_sys),
        u'configfile':"/home/meng/%s/.config"%(project_sys),
        u'checksum':"/home/meng/%s/include/checksum.h"%(project_sys),
        u'maketime':"/home/meng/%s/include/maketime.h"%(project_sys),
        u'LogoFile':"/home/meng/%s/tv-ap/dvb/ui2/logo/LOGO_BLACK_16_9.jpg"%(project_sys),
        u'errFile':"/home/meng/%s/err.txt"%(project_sys),
    }
    return py_replace_dat_dic
