# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propq',
            name='brightness_osd0_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd0_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd0_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd0_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd0_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd0_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd0_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd0_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd0_USB',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd0_USB'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd0_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd0_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd0_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd0_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd100_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd100_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd100_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd100_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd100_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd100_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd100_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd100_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd100_USB',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd100_USB'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd100_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd100_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd100_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd100_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd25_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd25_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd25_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd25_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd25_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd25_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd25_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd25_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd25_USB',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd25_USB'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd25_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd25_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd25_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd25_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd50_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd50_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd50_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd50_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd50_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd50_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd50_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd50_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd50_USB',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd50_USB'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd50_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd50_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd50_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd50_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd75_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd75_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd75_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd75_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd75_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd75_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd75_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd75_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd75_USB',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd75_USB'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd75_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd75_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd75_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd75_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_gainb_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_gainb_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_gainb_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_gainb_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_gainb_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_gainb_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_gainb_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_gainb_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_gainb_USB',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_gainb_USB'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_gainb_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_gainb_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_gainb_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_gainb_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_gaing_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_gaing_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_gaing_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_gaing_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_gaing_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_gaing_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_gaing_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_gaing_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_gaing_USB',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_gaing_USB'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_gaing_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_gaing_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_gaing_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_gaing_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_gainr_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_gainr_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_gainr_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_gainr_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_gainr_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_gainr_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_gainr_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_gainr_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_gainr_USB',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_gainr_USB'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_gainr_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_gainr_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_gainr_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_gainr_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_offsetb_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_offsetb_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_offsetb_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_offsetb_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_offsetb_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_offsetb_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_offsetb_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_offsetb_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_offsetb_USB',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_offsetb_USB'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_offsetb_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_offsetb_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_offsetb_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_offsetb_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_offsetg_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_offsetg_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_offsetg_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_offsetg_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_offsetg_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_offsetg_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_offsetg_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_offsetg_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_offsetg_USB',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_offsetg_USB'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_offsetg_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_offsetg_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_offsetg_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_offsetg_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_offsetr_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_offsetr_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_offsetr_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_offsetr_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_offsetr_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_offsetr_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_offsetr_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_offsetr_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_offsetr_USB',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_offsetr_USB'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_offsetr_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_offsetr_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_offsetr_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_offsetr_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd0_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd0_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd0_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd0_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd0_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd0_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd0_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd0_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd0_USB',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd0_USB'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd0_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd0_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd0_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd0_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd100_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd100_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd100_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd100_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd100_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd100_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd100_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd100_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd100_USB',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd100_USB'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd100_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd100_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd100_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd100_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd25_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd25_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd25_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd25_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd25_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd25_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd25_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd25_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd25_USB',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd25_USB'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd25_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd25_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd25_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd25_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd50_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd50_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd50_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd50_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd50_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd50_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd50_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd50_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd50_USB',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd50_USB'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd50_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd50_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd50_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd50_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd75_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd75_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd75_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd75_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd75_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd75_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd75_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd75_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd75_USB',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd75_USB'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd75_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd75_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd75_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd75_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='ibc_b',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='ibc_b'),
        ),
        migrations.AddField(
            model_name='propq',
            name='ibc_by',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='ibc_by'),
        ),
        migrations.AddField(
            model_name='propq',
            name='ibc_c',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='ibc_c'),
        ),
        migrations.AddField(
            model_name='propq',
            name='ibc_f',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='ibc_f'),
        ),
        migrations.AddField(
            model_name='propq',
            name='ibc_g',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='ibc_g'),
        ),
        migrations.AddField(
            model_name='propq',
            name='ibc_gy',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='ibc_gy'),
        ),
        migrations.AddField(
            model_name='propq',
            name='ibc_m',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='ibc_m'),
        ),
        migrations.AddField(
            model_name='propq',
            name='ibc_r',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='ibc_r'),
        ),
        migrations.AddField(
            model_name='propq',
            name='ibc_y',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='ibc_y'),
        ),
        migrations.AddField(
            model_name='propq',
            name='icc_b',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='icc_b'),
        ),
        migrations.AddField(
            model_name='propq',
            name='icc_by',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='icc_by'),
        ),
        migrations.AddField(
            model_name='propq',
            name='icc_c',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='icc_c'),
        ),
        migrations.AddField(
            model_name='propq',
            name='icc_f',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='icc_f'),
        ),
        migrations.AddField(
            model_name='propq',
            name='icc_g',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='icc_g'),
        ),
        migrations.AddField(
            model_name='propq',
            name='icc_gy',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='icc_gy'),
        ),
        migrations.AddField(
            model_name='propq',
            name='icc_m',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='icc_m'),
        ),
        migrations.AddField(
            model_name='propq',
            name='icc_r',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='icc_r'),
        ),
        migrations.AddField(
            model_name='propq',
            name='icc_y',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='icc_y'),
        ),
        migrations.AddField(
            model_name='propq',
            name='ihc_b',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='ihc_b'),
        ),
        migrations.AddField(
            model_name='propq',
            name='ihc_by',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='ihc_by'),
        ),
        migrations.AddField(
            model_name='propq',
            name='ihc_c',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='ihc_c'),
        ),
        migrations.AddField(
            model_name='propq',
            name='ihc_f',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='ihc_f'),
        ),
        migrations.AddField(
            model_name='propq',
            name='ihc_g',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='ihc_g'),
        ),
        migrations.AddField(
            model_name='propq',
            name='ihc_gy',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='ihc_gy'),
        ),
        migrations.AddField(
            model_name='propq',
            name='ihc_m',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='ihc_m'),
        ),
        migrations.AddField(
            model_name='propq',
            name='ihc_r',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='ihc_r'),
        ),
        migrations.AddField(
            model_name='propq',
            name='ihc_y',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='ihc_y'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_gainb_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_gainb_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_gainb_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_gainb_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_gainb_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_gainb_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_gainb_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_gainb_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_gainb_USB',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_gainb_USB'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_gainb_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_gainb_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_gainb_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_gainb_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_gaing_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_gaing_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_gaing_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_gaing_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_gaing_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_gaing_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_gaing_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_gaing_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_gaing_USB',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_gaing_USB'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_gaing_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_gaing_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_gaing_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_gaing_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_gainr_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_gainr_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_gainr_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_gainr_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_gainr_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_gainr_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_gainr_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_gainr_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_gainr_USB',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_gainr_USB'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_gainr_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_gainr_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_gainr_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_gainr_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_offsetb_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_offsetb_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_offsetb_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_offsetb_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_offsetb_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_offsetb_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_offsetb_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_offsetb_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_offsetb_USB',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_offsetb_USB'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_offsetb_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_offsetb_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_offsetb_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_offsetb_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_offsetg_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_offsetg_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_offsetg_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_offsetg_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_offsetg_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_offsetg_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_offsetg_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_offsetg_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_offsetg_USB',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_offsetg_USB'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_offsetg_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_offsetg_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_offsetg_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_offsetg_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_offsetr_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_offsetr_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_offsetr_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_offsetr_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_offsetr_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_offsetr_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_offsetr_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_offsetr_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_offsetr_USB',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_offsetr_USB'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_offsetr_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_offsetr_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_offsetr_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_offsetr_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd0_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd0_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd0_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd0_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd0_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd0_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd0_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd0_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd0_USB',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd0_USB'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd0_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd0_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd0_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd0_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd100_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd100_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd100_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd100_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd100_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd100_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd100_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd100_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd100_USB',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd100_USB'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd100_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd100_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd100_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd100_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd25_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd25_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd25_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd25_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd25_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd25_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd25_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd25_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd25_USB',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd25_USB'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd25_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd25_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd25_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd25_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd50_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd50_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd50_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd50_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd50_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd50_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd50_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd50_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd50_USB',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd50_USB'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd50_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd50_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd50_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd50_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd75_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd75_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd75_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd75_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd75_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd75_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd75_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd75_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd75_USB',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd75_USB'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd75_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd75_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd75_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd75_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd0_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd0_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd0_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd0_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd0_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd0_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd0_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd0_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd0_USB',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd0_USB'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd0_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd0_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd0_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd0_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd100_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd100_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd100_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd100_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd100_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd100_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd100_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd100_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd100_USB',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd100_USB'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd100_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd100_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd100_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd100_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd25_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd25_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd25_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd25_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd25_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd25_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd25_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd25_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd25_USB',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd25_USB'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd25_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd25_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd25_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd25_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd50_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd50_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd50_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd50_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd50_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd50_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd50_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd50_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd50_USB',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd50_USB'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd50_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd50_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd50_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd50_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd75_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd75_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd75_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd75_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd75_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd75_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd75_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd75_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd75_USB',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd75_USB'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd75_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd75_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd75_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd75_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd0_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd0_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd0_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd0_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd0_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd0_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd0_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd0_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd0_USB',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd0_USB'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd0_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd0_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd0_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd0_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd100_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd100_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd100_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd100_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd100_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd100_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd100_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd100_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd100_USB',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd100_USB'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd100_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd100_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd100_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd100_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd25_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd25_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd25_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd25_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd25_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd25_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd25_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd25_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd25_USB',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd25_USB'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd25_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd25_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd25_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd25_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd50_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd50_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd50_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd50_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd50_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd50_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd50_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd50_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd50_USB',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd50_USB'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd50_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd50_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd50_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd50_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd75_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd75_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd75_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd75_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd75_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd75_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd75_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd75_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd75_USB',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd75_USB'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd75_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd75_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd75_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd75_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_gainb_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_gainb_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_gainb_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_gainb_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_gainb_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_gainb_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_gainb_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_gainb_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_gainb_USB',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_gainb_USB'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_gainb_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_gainb_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_gainb_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_gainb_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_gaing_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_gaing_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_gaing_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_gaing_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_gaing_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_gaing_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_gaing_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_gaing_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_gaing_USB',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_gaing_USB'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_gaing_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_gaing_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_gaing_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_gaing_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_gainr_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_gainr_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_gainr_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_gainr_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_gainr_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_gainr_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_gainr_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_gainr_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_gainr_USB',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_gainr_USB'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_gainr_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_gainr_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_gainr_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_gainr_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_offsetb_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_offsetb_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_offsetb_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_offsetb_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_offsetb_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_offsetb_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_offsetb_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_offsetb_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_offsetb_USB',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_offsetb_USB'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_offsetb_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_offsetb_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_offsetb_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_offsetb_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_offsetg_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_offsetg_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_offsetg_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_offsetg_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_offsetg_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_offsetg_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_offsetg_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_offsetg_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_offsetg_USB',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_offsetg_USB'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_offsetg_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_offsetg_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_offsetg_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_offsetg_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_offsetr_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_offsetr_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_offsetr_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_offsetr_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_offsetr_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_offsetr_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_offsetr_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_offsetr_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_offsetr_USB',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_offsetr_USB'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_offsetr_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_offsetr_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_offsetr_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_offsetr_YPBPR'),
        ),
    ]
