# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_auto_20170705_0228'),
    ]

    operations = [
        migrations.CreateModel(
            name='power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_on_mode', models.CharField(default='', max_length=256, verbose_name='power_on_mode')),
            ],
        ),
    ]
