# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 01:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_auto_20170705_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloudpanel',
            old_name='panel_black_white_change',
            new_name='enable_black_white_change',
        ),
        migrations.RenameField(
            model_name='cloudpanel',
            old_name='panel_eveb_gb',
            new_name='panel_swap_even_gb',
        ),
        migrations.RenameField(
            model_name='cloudpanel',
            old_name='panel_even_ml',
            new_name='panel_swap_even_ml',
        ),
        migrations.RenameField(
            model_name='cloudpanel',
            old_name='panel_even_rb',
            new_name='panel_swap_even_rb',
        ),
        migrations.RenameField(
            model_name='cloudpanel',
            old_name='panel_even_rg',
            new_name='panel_swap_even_rg',
        ),
        migrations.RenameField(
            model_name='cloudpanel',
            old_name='panel_odd_gb',
            new_name='panel_swap_odd_gb',
        ),
        migrations.RenameField(
            model_name='cloudpanel',
            old_name='panel_odd_rb',
            new_name='panel_swap_odd_rb',
        ),
        migrations.RenameField(
            model_name='cloudpanel',
            old_name='panel_odd_rg',
            new_name='panel_swap_odd_rg',
        ),
        migrations.RenameField(
            model_name='propanel',
            old_name='panel_black_white_change',
            new_name='enable_black_white_change',
        ),
        migrations.RenameField(
            model_name='propanel',
            old_name='panel_eveb_gb',
            new_name='panel_swap_even_gb',
        ),
        migrations.RenameField(
            model_name='propanel',
            old_name='panel_even_ml',
            new_name='panel_swap_even_ml',
        ),
        migrations.RenameField(
            model_name='propanel',
            old_name='panel_even_rb',
            new_name='panel_swap_even_rb',
        ),
        migrations.RenameField(
            model_name='propanel',
            old_name='panel_even_rg',
            new_name='panel_swap_even_rg',
        ),
        migrations.RenameField(
            model_name='propanel',
            old_name='panel_odd_gb',
            new_name='panel_swap_odd_gb',
        ),
        migrations.RenameField(
            model_name='propanel',
            old_name='panel_odd_rb',
            new_name='panel_swap_odd_rb',
        ),
        migrations.RenameField(
            model_name='propanel',
            old_name='panel_odd_rg',
            new_name='panel_swap_odd_rg',
        ),
    ]
