# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_auto_20170706_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudpanel',
            name='panel_out_timing_mode',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='\u53d8\u6362\u6a21\u5f0f'),
        ),
        migrations.AlterField(
            model_name='propanel',
            name='panel_out_timing_mode',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='\u53d8\u6362\u6a21\u5f0f'),
        ),
    ]
