# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 02:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_auto_20170706_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloudpq',
            name='ibc_by',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='ibc_gy',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='icc_by',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='icc_gy',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='ihc_by',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='ihc_gy',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='ibc_by',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='ibc_gy',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='icc_by',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='icc_gy',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='ihc_by',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='ihc_gy',
        ),
    ]
