# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_auto_20170707_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloudpq',
            name='brightness_osd0_USB',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='brightness_osd100_USB',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='brightness_osd25_USB',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='brightness_osd50_USB',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='brightness_osd75_USB',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_gainb_USB',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_gaing_USB',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_gainr_USB',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_offsetb_USB',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_offsetg_USB',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_offsetr_USB',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='contrast_osd0_USB',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='contrast_osd100_USB',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='contrast_osd25_USB',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='contrast_osd50_USB',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='contrast_osd75_USB',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='normal_gainb_USB',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='normal_gaing_USB',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='normal_gainr_USB',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='normal_offsetb_USB',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='normal_offsetg_USB',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='normal_offsetr_USB',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='saturation_osd0_USB',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='saturation_osd100_USB',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='saturation_osd25_USB',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='saturation_osd50_USB',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='saturation_osd75_USB',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='sharpness_osd0_USB',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='sharpness_osd100_USB',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='sharpness_osd25_USB',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='sharpness_osd50_USB',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='sharpness_osd75_USB',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd0_USB',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd100_USB',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd25_USB',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd50_USB',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd75_USB',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='warm_gainb_USB',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='warm_gaing_USB',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='warm_gainr_USB',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='warm_offsetb_USB',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='warm_offsetg_USB',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='warm_offsetr_USB',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='brightness_osd0_USB',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='brightness_osd100_USB',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='brightness_osd25_USB',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='brightness_osd50_USB',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='brightness_osd75_USB',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_gainb_USB',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_gaing_USB',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_gainr_USB',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_offsetb_USB',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_offsetg_USB',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_offsetr_USB',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='contrast_osd0_USB',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='contrast_osd100_USB',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='contrast_osd25_USB',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='contrast_osd50_USB',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='contrast_osd75_USB',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='normal_gainb_USB',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='normal_gaing_USB',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='normal_gainr_USB',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='normal_offsetb_USB',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='normal_offsetg_USB',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='normal_offsetr_USB',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='saturation_osd0_USB',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='saturation_osd100_USB',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='saturation_osd25_USB',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='saturation_osd50_USB',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='saturation_osd75_USB',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='sharpness_osd0_USB',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='sharpness_osd100_USB',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='sharpness_osd25_USB',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='sharpness_osd50_USB',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='sharpness_osd75_USB',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd0_USB',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd100_USB',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd25_USB',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd50_USB',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd75_USB',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='warm_gainb_USB',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='warm_gaing_USB',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='warm_gainr_USB',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='warm_offsetb_USB',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='warm_offsetg_USB',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='warm_offsetr_USB',
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='brightness_osd0_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd0_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='brightness_osd0_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd0_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='brightness_osd0_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd0_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='brightness_osd0_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd0_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='brightness_osd100_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd100_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='brightness_osd100_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd100_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='brightness_osd100_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd100_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='brightness_osd100_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd100_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='brightness_osd25_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd25_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='brightness_osd25_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd25_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='brightness_osd25_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd25_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='brightness_osd25_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd25_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='brightness_osd50_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd50_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='brightness_osd50_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd50_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='brightness_osd50_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd50_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='brightness_osd50_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd50_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='brightness_osd75_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd75_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='brightness_osd75_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd75_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='brightness_osd75_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd75_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='brightness_osd75_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd75_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cold_gainb_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_gainb_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cold_gainb_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_gainb_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cold_gainb_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_gainb_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cold_gainb_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_gainb_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cold_gaing_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_gaing_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cold_gaing_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_gaing_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cold_gaing_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_gaing_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cold_gaing_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_gaing_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cold_gainr_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_gainr_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cold_gainr_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_gainr_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cold_gainr_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_gainr_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cold_gainr_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_gainr_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cold_offsetb_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_offsetb_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cold_offsetb_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_offsetb_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cold_offsetb_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_offsetb_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cold_offsetb_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_offsetb_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cold_offsetg_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_offsetg_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cold_offsetg_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_offsetg_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cold_offsetg_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_offsetg_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cold_offsetg_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_offsetg_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cold_offsetr_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_offsetr_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cold_offsetr_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_offsetr_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cold_offsetr_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_offsetr_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cold_offsetr_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_offsetr_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='contrast_osd0_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd0_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='contrast_osd0_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd0_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='contrast_osd0_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd0_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='contrast_osd0_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd0_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='contrast_osd100_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd100_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='contrast_osd100_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd100_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='contrast_osd100_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd100_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='contrast_osd100_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd100_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='contrast_osd25_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd25_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='contrast_osd25_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd25_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='contrast_osd25_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd25_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='contrast_osd25_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd25_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='contrast_osd50_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd50_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='contrast_osd50_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd50_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='contrast_osd50_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd50_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='contrast_osd50_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd50_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='contrast_osd75_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd75_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='contrast_osd75_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd75_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='contrast_osd75_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd75_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='contrast_osd75_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd75_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='normal_gainb_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_gainb_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='normal_gainb_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_gainb_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='normal_gainb_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_gainb_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='normal_gainb_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_gainb_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='normal_gaing_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_gaing_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='normal_gaing_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_gaing_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='normal_gaing_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_gaing_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='normal_gaing_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_gaing_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='normal_gainr_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_gainr_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='normal_gainr_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_gainr_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='normal_gainr_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_gainr_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='normal_gainr_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_gainr_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='normal_offsetb_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_offsetb_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='normal_offsetb_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_offsetb_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='normal_offsetb_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_offsetb_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='normal_offsetb_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_offsetb_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='normal_offsetg_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_offsetg_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='normal_offsetg_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_offsetg_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='normal_offsetg_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_offsetg_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='normal_offsetg_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_offsetg_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='normal_offsetr_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_offsetr_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='normal_offsetr_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_offsetr_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='normal_offsetr_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_offsetr_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='normal_offsetr_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_offsetr_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='saturation_osd0_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd0_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='saturation_osd0_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd0_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='saturation_osd0_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd0_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='saturation_osd0_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd0_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='saturation_osd100_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd100_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='saturation_osd100_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd100_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='saturation_osd100_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd100_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='saturation_osd100_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd100_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='saturation_osd25_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd25_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='saturation_osd25_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd25_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='saturation_osd25_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd25_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='saturation_osd25_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd25_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='saturation_osd50_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd50_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='saturation_osd50_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd50_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='saturation_osd50_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd50_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='saturation_osd50_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd50_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='saturation_osd75_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd75_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='saturation_osd75_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd75_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='saturation_osd75_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd75_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='saturation_osd75_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd75_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='sharpness_osd0_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd0_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='sharpness_osd0_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd0_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='sharpness_osd0_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd0_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='sharpness_osd0_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd0_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='sharpness_osd100_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd100_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='sharpness_osd100_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd100_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='sharpness_osd100_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd100_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='sharpness_osd100_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd100_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='sharpness_osd25_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd25_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='sharpness_osd25_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd25_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='sharpness_osd25_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd25_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='sharpness_osd25_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd25_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='sharpness_osd50_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd50_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='sharpness_osd50_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd50_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='sharpness_osd50_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd50_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='sharpness_osd50_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd50_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='sharpness_osd75_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd75_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='sharpness_osd75_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd75_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='sharpness_osd75_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd75_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='sharpness_osd75_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd75_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='tint_osd0_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd0_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='tint_osd0_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd0_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='tint_osd0_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd0_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='tint_osd0_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd0_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='tint_osd100_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd100_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='tint_osd100_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd100_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='tint_osd100_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd100_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='tint_osd100_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd100_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='tint_osd25_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd25_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='tint_osd25_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd25_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='tint_osd25_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd25_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='tint_osd25_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd25_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='tint_osd50_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd50_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='tint_osd50_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd50_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='tint_osd50_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd50_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='tint_osd50_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd50_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='tint_osd75_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd75_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='tint_osd75_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd75_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='tint_osd75_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd75_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='tint_osd75_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd75_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='warm_gainb_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_gainb_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='warm_gainb_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_gainb_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='warm_gainb_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_gainb_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='warm_gainb_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_gainb_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='warm_gaing_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_gaing_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='warm_gaing_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_gaing_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='warm_gaing_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_gaing_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='warm_gaing_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_gaing_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='warm_gainr_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_gainr_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='warm_gainr_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_gainr_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='warm_gainr_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_gainr_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='warm_gainr_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_gainr_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='warm_offsetb_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_offsetb_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='warm_offsetb_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_offsetb_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='warm_offsetb_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_offsetb_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='warm_offsetb_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_offsetb_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='warm_offsetg_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_offsetg_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='warm_offsetg_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_offsetg_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='warm_offsetg_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_offsetg_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='warm_offsetg_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_offsetg_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='warm_offsetr_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_offsetr_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='warm_offsetr_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_offsetr_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='warm_offsetr_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_offsetr_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='warm_offsetr_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_offsetr_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd0_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd0_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd0_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd0_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd0_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd0_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd0_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd0_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd100_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd100_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd100_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd100_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd100_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd100_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd100_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd100_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd25_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd25_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd25_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd25_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd25_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd25_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd25_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd25_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd50_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd50_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd50_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd50_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd50_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd50_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd50_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd50_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd75_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd75_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd75_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd75_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd75_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd75_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='brightness_osd75_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='brightness_osd75_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_gainb_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_gainb_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_gainb_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_gainb_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_gainb_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_gainb_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_gainb_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_gainb_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_gaing_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_gaing_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_gaing_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_gaing_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_gaing_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_gaing_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_gaing_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_gaing_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_gainr_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_gainr_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_gainr_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_gainr_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_gainr_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_gainr_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_gainr_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_gainr_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_offsetb_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_offsetb_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_offsetb_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_offsetb_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_offsetb_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_offsetb_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_offsetb_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_offsetb_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_offsetg_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_offsetg_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_offsetg_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_offsetg_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_offsetg_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_offsetg_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_offsetg_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_offsetg_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_offsetr_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_offsetr_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_offsetr_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_offsetr_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_offsetr_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_offsetr_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cold_offsetr_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cold_offsetr_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd0_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd0_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd0_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd0_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd0_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd0_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd0_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd0_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd100_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd100_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd100_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd100_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd100_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd100_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd100_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd100_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd25_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd25_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd25_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd25_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd25_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd25_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd25_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd25_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd50_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd50_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd50_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd50_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd50_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd50_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd50_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd50_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd75_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd75_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd75_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd75_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd75_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd75_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='contrast_osd75_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='contrast_osd75_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_gainb_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_gainb_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_gainb_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_gainb_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_gainb_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_gainb_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_gainb_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_gainb_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_gaing_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_gaing_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_gaing_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_gaing_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_gaing_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_gaing_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_gaing_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_gaing_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_gainr_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_gainr_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_gainr_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_gainr_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_gainr_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_gainr_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_gainr_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_gainr_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_offsetb_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_offsetb_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_offsetb_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_offsetb_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_offsetb_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_offsetb_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_offsetb_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_offsetb_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_offsetg_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_offsetg_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_offsetg_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_offsetg_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_offsetg_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_offsetg_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_offsetg_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_offsetg_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_offsetr_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_offsetr_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_offsetr_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_offsetr_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_offsetr_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_offsetr_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='normal_offsetr_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='normal_offsetr_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd0_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd0_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd0_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd0_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd0_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd0_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd0_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd0_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd100_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd100_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd100_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd100_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd100_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd100_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd100_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd100_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd25_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd25_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd25_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd25_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd25_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd25_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd25_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd25_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd50_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd50_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd50_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd50_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd50_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd50_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd50_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd50_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd75_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd75_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd75_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd75_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd75_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd75_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='saturation_osd75_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='saturation_osd75_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd0_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd0_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd0_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd0_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd0_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd0_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd0_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd0_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd100_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd100_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd100_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd100_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd100_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd100_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd100_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd100_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd25_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd25_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd25_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd25_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd25_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd25_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd25_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd25_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd50_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd50_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd50_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd50_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd50_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd50_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd50_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd50_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd75_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd75_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd75_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd75_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd75_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd75_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='sharpness_osd75_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='sharpness_osd75_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd0_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd0_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd0_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd0_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd0_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd0_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd0_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd0_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd100_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd100_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd100_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd100_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd100_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd100_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd100_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd100_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd25_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd25_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd25_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd25_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd25_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd25_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd25_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd25_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd50_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd50_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd50_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd50_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd50_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd50_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd50_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd50_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd75_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd75_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd75_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd75_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd75_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd75_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='tint_osd75_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='tint_osd75_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_gainb_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_gainb_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_gainb_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_gainb_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_gainb_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_gainb_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_gainb_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_gainb_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_gaing_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_gaing_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_gaing_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_gaing_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_gaing_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_gaing_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_gaing_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_gaing_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_gainr_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_gainr_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_gainr_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_gainr_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_gainr_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_gainr_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_gainr_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_gainr_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_offsetb_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_offsetb_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_offsetb_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_offsetb_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_offsetb_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_offsetb_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_offsetb_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_offsetb_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_offsetg_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_offsetg_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_offsetg_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_offsetg_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_offsetg_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_offsetg_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_offsetg_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_offsetg_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_offsetr_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_offsetr_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_offsetr_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_offsetr_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_offsetr_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_offsetr_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='warm_offsetr_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='warm_offsetr_SVIDEO'),
        ),
    ]
