# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0008_auto_20170707_0321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd0_ATV',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd0_AV',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd0_DMP',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd0_DTV',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd0_DVD',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd0_HDMI',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd0_SCART',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd0_SVIDEO',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd0_VGA',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd0_YPBPR',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd100_ATV',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd100_AV',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd100_DMP',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd100_DTV',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd100_DVD',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd100_HDMI',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd100_SCART',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd100_SVIDEO',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd100_VGA',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd100_YPBPR',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd25_ATV',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd25_AV',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd25_DMP',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd25_DTV',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd25_DVD',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd25_HDMI',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd25_SCART',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd25_SVIDEO',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd25_VGA',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd25_YPBPR',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd50_ATV',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd50_AV',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd50_DMP',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd50_DTV',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd50_DVD',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd50_HDMI',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd50_SCART',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd50_SVIDEO',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd50_VGA',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd50_YPBPR',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd75_ATV',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd75_AV',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd75_DMP',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd75_DTV',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd75_DVD',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd75_HDMI',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd75_SCART',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd75_SVIDEO',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd75_VGA',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='tint_osd75_YPBPR',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd0_ATV',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd0_AV',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd0_DMP',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd0_DTV',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd0_DVD',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd0_HDMI',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd0_SCART',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd0_SVIDEO',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd0_VGA',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd0_YPBPR',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd100_ATV',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd100_AV',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd100_DMP',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd100_DTV',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd100_DVD',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd100_HDMI',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd100_SCART',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd100_SVIDEO',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd100_VGA',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd100_YPBPR',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd25_ATV',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd25_AV',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd25_DMP',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd25_DTV',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd25_DVD',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd25_HDMI',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd25_SCART',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd25_SVIDEO',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd25_VGA',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd25_YPBPR',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd50_ATV',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd50_AV',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd50_DMP',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd50_DTV',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd50_DVD',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd50_HDMI',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd50_SCART',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd50_SVIDEO',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd50_VGA',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd50_YPBPR',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd75_ATV',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd75_AV',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd75_DMP',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd75_DTV',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd75_DVD',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd75_HDMI',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd75_SCART',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd75_SVIDEO',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd75_VGA',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='tint_osd75_YPBPR',
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='hue_osd0_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd0_ATV'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='hue_osd0_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd0_AV'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='hue_osd0_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd0_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='hue_osd0_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd0_DTV'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='hue_osd0_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd0_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='hue_osd0_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd0_HDMI'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='hue_osd0_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd0_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='hue_osd0_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd0_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='hue_osd0_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd0_VGA'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='hue_osd0_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd0_YPBPR'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='hue_osd100_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd100_ATV'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='hue_osd100_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd100_AV'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='hue_osd100_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd100_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='hue_osd100_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd100_DTV'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='hue_osd100_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd100_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='hue_osd100_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd100_HDMI'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='hue_osd100_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd100_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='hue_osd100_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd100_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='hue_osd100_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd100_VGA'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='hue_osd100_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd100_YPBPR'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='hue_osd25_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd25_ATV'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='hue_osd25_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd25_AV'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='hue_osd25_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd25_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='hue_osd25_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd25_DTV'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='hue_osd25_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd25_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='hue_osd25_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd25_HDMI'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='hue_osd25_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd25_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='hue_osd25_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd25_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='hue_osd25_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd25_VGA'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='hue_osd25_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd25_YPBPR'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='hue_osd50_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd50_ATV'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='hue_osd50_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd50_AV'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='hue_osd50_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd50_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='hue_osd50_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd50_DTV'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='hue_osd50_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd50_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='hue_osd50_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd50_HDMI'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='hue_osd50_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd50_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='hue_osd50_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd50_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='hue_osd50_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd50_VGA'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='hue_osd50_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd50_YPBPR'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='hue_osd75_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd75_ATV'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='hue_osd75_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd75_AV'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='hue_osd75_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd75_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='hue_osd75_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd75_DTV'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='hue_osd75_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd75_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='hue_osd75_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd75_HDMI'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='hue_osd75_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd75_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='hue_osd75_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd75_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='hue_osd75_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd75_VGA'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='hue_osd75_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd75_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='hue_osd0_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd0_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='hue_osd0_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd0_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='hue_osd0_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd0_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='hue_osd0_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd0_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='hue_osd0_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd0_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='hue_osd0_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd0_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='hue_osd0_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd0_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='hue_osd0_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd0_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='hue_osd0_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd0_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='hue_osd0_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd0_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='hue_osd100_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd100_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='hue_osd100_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd100_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='hue_osd100_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd100_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='hue_osd100_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd100_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='hue_osd100_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd100_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='hue_osd100_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd100_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='hue_osd100_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd100_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='hue_osd100_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd100_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='hue_osd100_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd100_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='hue_osd100_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd100_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='hue_osd25_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd25_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='hue_osd25_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd25_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='hue_osd25_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd25_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='hue_osd25_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd25_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='hue_osd25_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd25_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='hue_osd25_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd25_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='hue_osd25_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd25_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='hue_osd25_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd25_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='hue_osd25_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd25_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='hue_osd25_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd25_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='hue_osd50_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd50_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='hue_osd50_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd50_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='hue_osd50_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd50_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='hue_osd50_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd50_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='hue_osd50_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd50_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='hue_osd50_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd50_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='hue_osd50_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd50_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='hue_osd50_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd50_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='hue_osd50_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd50_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='hue_osd50_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd50_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='hue_osd75_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd75_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='hue_osd75_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd75_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='hue_osd75_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd75_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='hue_osd75_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd75_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='hue_osd75_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd75_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='hue_osd75_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd75_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='hue_osd75_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd75_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='hue_osd75_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd75_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='hue_osd75_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd75_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='hue_osd75_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='hue_osd75_YPBPR'),
        ),
    ]
