# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0009_auto_20170707_0551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_gainb_ATV',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_gainb_AV',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_gainb_DMP',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_gainb_DTV',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_gainb_DVD',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_gainb_HDMI',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_gainb_SCART',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_gainb_SVIDEO',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_gainb_VGA',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_gainb_YPBPR',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_gaing_ATV',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_gaing_AV',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_gaing_DMP',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_gaing_DTV',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_gaing_DVD',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_gaing_HDMI',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_gaing_SCART',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_gaing_SVIDEO',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_gaing_VGA',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_gaing_YPBPR',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_gainr_ATV',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_gainr_AV',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_gainr_DMP',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_gainr_DTV',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_gainr_DVD',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_gainr_HDMI',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_gainr_SCART',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_gainr_SVIDEO',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_gainr_VGA',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_gainr_YPBPR',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_offsetb_ATV',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_offsetb_AV',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_offsetb_DMP',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_offsetb_DTV',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_offsetb_DVD',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_offsetb_HDMI',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_offsetb_SCART',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_offsetb_SVIDEO',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_offsetb_VGA',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_offsetb_YPBPR',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_offsetg_ATV',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_offsetg_AV',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_offsetg_DMP',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_offsetg_DTV',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_offsetg_DVD',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_offsetg_HDMI',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_offsetg_SCART',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_offsetg_SVIDEO',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_offsetg_VGA',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_offsetg_YPBPR',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_offsetr_ATV',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_offsetr_AV',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_offsetr_DMP',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_offsetr_DTV',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_offsetr_DVD',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_offsetr_HDMI',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_offsetr_SCART',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_offsetr_SVIDEO',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_offsetr_VGA',
        ),
        migrations.RemoveField(
            model_name='cloudpq',
            name='cold_offsetr_YPBPR',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_gainb_ATV',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_gainb_AV',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_gainb_DMP',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_gainb_DTV',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_gainb_DVD',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_gainb_HDMI',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_gainb_SCART',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_gainb_SVIDEO',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_gainb_VGA',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_gainb_YPBPR',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_gaing_ATV',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_gaing_AV',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_gaing_DMP',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_gaing_DTV',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_gaing_DVD',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_gaing_HDMI',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_gaing_SCART',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_gaing_SVIDEO',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_gaing_VGA',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_gaing_YPBPR',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_gainr_ATV',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_gainr_AV',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_gainr_DMP',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_gainr_DTV',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_gainr_DVD',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_gainr_HDMI',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_gainr_SCART',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_gainr_SVIDEO',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_gainr_VGA',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_gainr_YPBPR',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_offsetb_ATV',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_offsetb_AV',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_offsetb_DMP',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_offsetb_DTV',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_offsetb_DVD',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_offsetb_HDMI',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_offsetb_SCART',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_offsetb_SVIDEO',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_offsetb_VGA',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_offsetb_YPBPR',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_offsetg_ATV',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_offsetg_AV',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_offsetg_DMP',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_offsetg_DTV',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_offsetg_DVD',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_offsetg_HDMI',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_offsetg_SCART',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_offsetg_SVIDEO',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_offsetg_VGA',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_offsetg_YPBPR',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_offsetr_ATV',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_offsetr_AV',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_offsetr_DMP',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_offsetr_DTV',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_offsetr_DVD',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_offsetr_HDMI',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_offsetr_SCART',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_offsetr_SVIDEO',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_offsetr_VGA',
        ),
        migrations.RemoveField(
            model_name='propq',
            name='cold_offsetr_YPBPR',
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_gainb_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gainb_ATV'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_gainb_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gainb_AV'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_gainb_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gainb_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_gainb_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gainb_DTV'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_gainb_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gainb_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_gainb_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gainb_HDMI'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_gainb_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gainb_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_gainb_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gainb_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_gainb_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gainb_VGA'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_gainb_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gainb_YPBPR'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_gaing_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gaing_ATV'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_gaing_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gaing_AV'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_gaing_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gaing_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_gaing_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gaing_DTV'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_gaing_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gaing_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_gaing_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gaing_HDMI'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_gaing_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gaing_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_gaing_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gaing_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_gaing_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gaing_VGA'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_gaing_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gaing_YPBPR'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_gainr_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gainr_ATV'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_gainr_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gainr_AV'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_gainr_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gainr_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_gainr_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gainr_DTV'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_gainr_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gainr_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_gainr_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gainr_HDMI'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_gainr_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gainr_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_gainr_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gainr_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_gainr_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gainr_VGA'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_gainr_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gainr_YPBPR'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_offsetb_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetb_ATV'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_offsetb_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetb_AV'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_offsetb_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetb_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_offsetb_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetb_DTV'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_offsetb_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetb_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_offsetb_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetb_HDMI'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_offsetb_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetb_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_offsetb_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetb_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_offsetb_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetb_VGA'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_offsetb_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetb_YPBPR'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_offsetg_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetg_ATV'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_offsetg_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetg_AV'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_offsetg_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetg_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_offsetg_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetg_DTV'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_offsetg_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetg_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_offsetg_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetg_HDMI'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_offsetg_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetg_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_offsetg_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetg_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_offsetg_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetg_VGA'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_offsetg_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetg_YPBPR'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_offsetr_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetr_ATV'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_offsetr_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetr_AV'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_offsetr_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetr_DMP'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_offsetr_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetr_DTV'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_offsetr_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetr_DVD'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_offsetr_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetr_HDMI'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_offsetr_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetr_SCART'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_offsetr_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetr_SVIDEO'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_offsetr_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetr_VGA'),
        ),
        migrations.AddField(
            model_name='cloudpq',
            name='cool_offsetr_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetr_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_gainb_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gainb_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_gainb_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gainb_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_gainb_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gainb_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_gainb_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gainb_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_gainb_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gainb_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_gainb_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gainb_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_gainb_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gainb_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_gainb_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gainb_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_gainb_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gainb_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_gainb_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gainb_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_gaing_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gaing_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_gaing_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gaing_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_gaing_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gaing_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_gaing_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gaing_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_gaing_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gaing_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_gaing_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gaing_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_gaing_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gaing_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_gaing_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gaing_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_gaing_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gaing_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_gaing_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gaing_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_gainr_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gainr_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_gainr_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gainr_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_gainr_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gainr_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_gainr_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gainr_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_gainr_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gainr_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_gainr_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gainr_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_gainr_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gainr_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_gainr_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gainr_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_gainr_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gainr_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_gainr_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_gainr_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_offsetb_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetb_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_offsetb_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetb_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_offsetb_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetb_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_offsetb_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetb_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_offsetb_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetb_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_offsetb_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetb_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_offsetb_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetb_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_offsetb_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetb_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_offsetb_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetb_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_offsetb_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetb_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_offsetg_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetg_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_offsetg_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetg_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_offsetg_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetg_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_offsetg_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetg_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_offsetg_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetg_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_offsetg_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetg_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_offsetg_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetg_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_offsetg_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetg_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_offsetg_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetg_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_offsetg_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetg_YPBPR'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_offsetr_ATV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetr_ATV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_offsetr_AV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetr_AV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_offsetr_DMP',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetr_DMP'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_offsetr_DTV',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetr_DTV'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_offsetr_DVD',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetr_DVD'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_offsetr_HDMI',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetr_HDMI'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_offsetr_SCART',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetr_SCART'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_offsetr_SVIDEO',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetr_SVIDEO'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_offsetr_VGA',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetr_VGA'),
        ),
        migrations.AddField(
            model_name='propq',
            name='cool_offsetr_YPBPR',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='cool_offsetr_YPBPR'),
        ),
    ]
