# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0010_auto_20170707_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='default_logo',
            name='logo_src1',
            field=models.FileField(max_length=256, upload_to='./logo/default/', verbose_name='\u9884\u9009LOGO1\u8def\u5f84'),
        ),
        migrations.AlterField(
            model_name='default_logo',
            name='logo_src2',
            field=models.FileField(max_length=256, upload_to='./logo/default/', verbose_name='\u9884\u9009LOGO2\u8def\u5f84'),
        ),
        migrations.AlterField(
            model_name='default_logo',
            name='logo_src3',
            field=models.FileField(max_length=256, upload_to='./logo/default/', verbose_name='\u9884\u9009LOGO3\u8def\u5f84'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_pwd',
            field=models.CharField(blank=True, default='6ecf12b2cfaf1737f15d80560f6998f37c618c5e', max_length=256, verbose_name='user_pwd'),
        ),
    ]
