# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0011_auto_20170711_0734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloudpanel',
            old_name='panel_min_htoal',
            new_name='panel_min_htotal',
        ),
        migrations.RenameField(
            model_name='cloudpanel',
            old_name='panel_min_vhtotal',
            new_name='panel_min_vtotal',
        ),
        migrations.RemoveField(
            model_name='cloudpanel',
            name='panel_max_vhtotal',
        ),
        migrations.AddField(
            model_name='cloudpanel',
            name='panel_max_vtotal',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='\u573a\u6700\u5927\u503c'),
        ),
    ]
