# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0013_auto_20170712_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloudpanel',
            old_name='panel_vhtotal',
            new_name='panel_vtotal',
        ),
        migrations.RenameField(
            model_name='propanel',
            old_name='panel_vhtotal',
            new_name='panel_vtotal',
        ),
    ]
