# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0014_auto_20170712_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloudpanel',
            old_name='panel_heigth_define',
            new_name='panel_height_define',
        ),
        migrations.RenameField(
            model_name='propanel',
            old_name='panel_heigth_define',
            new_name='panel_height_define',
        ),
    ]
