# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0015_auto_20170712_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloudir',
            old_name='remote_chl_plus2',
            new_name='remote_channel_use_as_updown',
        ),
        migrations.RenameField(
            model_name='proremote1',
            old_name='remote_chl_plus2',
            new_name='remote_channel_use_as_updown',
        ),
        migrations.RenameField(
            model_name='proremote2',
            old_name='remote_chl_plus2',
            new_name='remote_channel_use_as_updown',
        ),
        migrations.RemoveField(
            model_name='cloudir',
            name='remote_chl_minus2',
        ),
        migrations.RemoveField(
            model_name='cloudir',
            name='remote_vol_minus2',
        ),
        migrations.RemoveField(
            model_name='cloudir',
            name='remote_vol_plus2',
        ),
        migrations.RemoveField(
            model_name='proremote1',
            name='remote_chl_minus2',
        ),
        migrations.RemoveField(
            model_name='proremote1',
            name='remote_vol_minus2',
        ),
        migrations.RemoveField(
            model_name='proremote1',
            name='remote_vol_plus2',
        ),
        migrations.RemoveField(
            model_name='proremote2',
            name='remote_chl_minus2',
        ),
        migrations.RemoveField(
            model_name='proremote2',
            name='remote_vol_minus2',
        ),
        migrations.RemoveField(
            model_name='proremote2',
            name='remote_vol_plus2',
        ),
        migrations.AddField(
            model_name='cloudir',
            name='remote_voluem_use_as_leftright',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='\u590d\u7528\u97f3\u91cf'),
        ),
        migrations.AddField(
            model_name='proremote1',
            name='remote_voluem_use_as_leftright',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='\u590d\u7528\u97f3\u91cf'),
        ),
        migrations.AddField(
            model_name='proremote2',
            name='remote_voluem_use_as_leftright',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='\u590d\u7528\u97f3\u91cf'),
        ),
    ]
