# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0016_auto_20170712_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloudir',
            old_name='remote_voluem_use_as_leftright',
            new_name='remote_volume_use_as_leftright',
        ),
        migrations.RenameField(
            model_name='proremote1',
            old_name='remote_voluem_use_as_leftright',
            new_name='remote_volume_use_as_leftright',
        ),
        migrations.RenameField(
            model_name='proremote2',
            old_name='remote_voluem_use_as_leftright',
            new_name='remote_volume_use_as_leftright',
        ),
    ]
