# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0017_auto_20170712_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudir',
            name='remote_header_code_time',
            field=models.CharField(blank=True, default='9000', max_length=10, verbose_name='\u9065\u63a7\u5934\u7801\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='proremote1',
            name='remote_header_code_time',
            field=models.CharField(blank=True, default='9000', max_length=10, verbose_name='\u4e3b\u9065\u63a7\u5934\u7801\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='proremote2',
            name='remote_header_code_time',
            field=models.CharField(blank=True, default='9000', max_length=10, verbose_name='\u526f\u9065\u63a7\u5934\u7801\u65f6\u95f4'),
        ),
    ]
