# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 03:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0018_auto_20170713_0051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloudir',
            old_name='remote_vga',
            new_name='remote_pc',
        ),
        migrations.RenameField(
            model_name='cloudir',
            old_name='remote_voluem_minus',
            new_name='remote_volume_minus',
        ),
        migrations.RenameField(
            model_name='proremote1',
            old_name='remote_vga',
            new_name='remote_pc',
        ),
        migrations.RenameField(
            model_name='proremote1',
            old_name='remote_voluem_minus',
            new_name='remote_volume_minus',
        ),
        migrations.RenameField(
            model_name='proremote2',
            old_name='remote_vga',
            new_name='remote_pc',
        ),
        migrations.RenameField(
            model_name='proremote2',
            old_name='remote_voluem_minus',
            new_name='remote_volume_minus',
        ),
    ]
