# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0019_auto_20170713_0307'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompileList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.CharField(blank=True, default='', max_length=10, verbose_name='\u9879\u76ee\u7f16\u53f7')),
                ('pro_statu', models.CharField(blank=True, default='0', max_length=10, verbose_name='\u9879\u76ee\u72b6\u6001')),
            ],
        ),
    ]
