# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0020_compilelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudproject',
            name='project_file',
            field=models.FileField(blank=True, upload_to=b'', verbose_name='\u7f16\u8bd1\u6587\u4ef6'),
        ),
    ]
