# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 06:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0022_auto_20170717_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_author',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='\u7528\u6237\u6743\u9650'),
        ),
        migrations.AlterField(
            model_name='collectproject',
            name='pro_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.CloudProject'),
        ),
    ]
