# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0023_auto_20170727_0615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collectlogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(verbose_name='\u7528\u6237id')),
            ],
            options={
                'verbose_name': 'LOGO',
                'verbose_name_plural': 'LOGO\u914d\u7f6e',
            },
        ),
        migrations.CreateModel(
            name='logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LOGOTime', models.CharField(default='', max_length=256, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('logo_name', models.CharField(blank=True, default='', max_length=256, verbose_name='LOGO\u540d\u79f0')),
                ('logo_src', models.FileField(max_length=256, upload_to='./logo/default/', verbose_name='LOGO\u8def\u5f84')),
            ],
            options={
                'verbose_name': 'LOGO',
                'verbose_name_plural': 'LOGO\u914d\u7f6e',
            },
        ),
        migrations.DeleteModel(
            name='Default_logo',
        ),
        migrations.AlterModelOptions(
            name='boardconfig',
            options={'verbose_name': '\u7248\u578b', 'verbose_name_plural': '\u7248\u578b\u914d\u7f6e'},
        ),
        migrations.AlterModelOptions(
            name='cloudir',
            options={'verbose_name': '\u9065\u63a7', 'verbose_name_plural': '\u9065\u63a7\u914d\u7f6e'},
        ),
        migrations.AlterModelOptions(
            name='cloudkeypad',
            options={'verbose_name': '\u6309\u952e', 'verbose_name_plural': '\u6309\u952e\u914d\u7f6e'},
        ),
        migrations.AlterModelOptions(
            name='cloudpanel',
            options={'verbose_name': '\u5c4f\u53c2', 'verbose_name_plural': '\u5c4f\u53c2\u914d\u7f6e'},
        ),
        migrations.AlterModelOptions(
            name='cloudpq',
            options={'verbose_name': 'PQ', 'verbose_name_plural': 'PQ\u914d\u7f6e'},
        ),
        migrations.AlterModelOptions(
            name='cloudproject',
            options={'verbose_name': '\u9879\u76ee', 'verbose_name_plural': '\u9879\u76ee\u914d\u7f6e'},
        ),
        migrations.AlterModelOptions(
            name='compilelist',
            options={'verbose_name': '\u7f16\u8bd1', 'verbose_name_plural': '\u7f16\u8bd1\u5217\u8868'},
        ),
        migrations.AlterModelOptions(
            name='languageconfig',
            options={'verbose_name': '\u8bed\u8a00', 'verbose_name_plural': '\u8bed\u8a00\u914d\u7f6e'},
        ),
        migrations.AlterModelOptions(
            name='power',
            options={'verbose_name': '\u4e0a\u7535\u6a21\u5f0f', 'verbose_name_plural': '\u4e0a\u7535\u914d\u7f6e'},
        ),
        migrations.AlterModelOptions(
            name='projectconfig',
            options={'verbose_name': '\u7c7b\u578b', 'verbose_name_plural': '\u7c7b\u578b\u914d\u7f6e'},
        ),
        migrations.AlterModelOptions(
            name='propq',
            options={'verbose_name': '\u9879\u76eePQ', 'verbose_name_plural': '\u9879\u76eePQ'},
        ),
        migrations.AlterModelOptions(
            name='systemconfig',
            options={'verbose_name': '\u5236\u5f0f', 'verbose_name_plural': '\u5236\u5f0f\u914d\u7f6e'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id'], 'verbose_name': '\u7528\u6237', 'verbose_name_plural': '\u7528\u6237\u8868'},
        ),
        migrations.AddField(
            model_name='logo',
            name='Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.User'),
        ),
        migrations.AddField(
            model_name='collectlogo',
            name='logo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.CloudPQ'),
        ),
    ]
