# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0024_auto_20170731_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectlogo',
            name='logo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.logo'),
        ),
    ]
