# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0025_auto_20170731_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudproject',
            name='logo_name',
            field=models.FileField(blank=True, default='', max_length=256, upload_to=b'', verbose_name='LOGO\u540d\u5b57'),
        ),
        migrations.AddField(
            model_name='cloudproject',
            name='notes',
            field=models.FileField(blank=True, max_length=256, upload_to=b'', verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='cloudproject',
            name='project_file',
            field=models.FileField(blank=True, max_length=256, upload_to=b'', verbose_name='\u7f16\u8bd1\u6587\u4ef6'),
        ),
    ]
