# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0027_auto_20170818_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudproject',
            name='language',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='\u8bed\u8a00'),
        ),
    ]
