# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0028_auto_20170819_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_language',
            field=models.CharField(blank=True, default='\u4e2d\u6587\u7b80\u4f53', max_length=20, verbose_name='\u8bed\u8a00'),
        ),
    ]
