# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0030_auto_20170822_1315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardconfig',
            options={'verbose_name': '\u677f\u578b', 'verbose_name_plural': '\u677f\u578b\u914d\u7f6e'},
        ),
        migrations.AddField(
            model_name='boardconfig',
            name='board_img1',
            field=models.FileField(blank=True, upload_to='./Images/board/', verbose_name='\u677f\u578b\u6b63\u9762\u56fe'),
        ),
        migrations.AddField(
            model_name='boardconfig',
            name='board_img2',
            field=models.FileField(blank=True, upload_to='./Images/board/', verbose_name='\u677f\u578b\u80cc\u9762\u56fe'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_icon',
            field=models.FileField(blank=True, upload_to='./Images/user/jdface/', verbose_name='\u7528\u6237\u5934\u50cf'),
        ),
    ]
