# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0032_auto_20170824_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudproject',
            name='compile_err',
            field=models.CharField(blank=True, max_length=256, verbose_name='\u9519\u8bef\u4fe1\u606f'),
        ),
    ]
